# Generated by Django 5.2.4 on 2025-08-03 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('#4ea7ff', 'blue'), ('#6ce272', 'green'), ('#ffd36c', 'yellow'), ('#ff7272', 'red'), ('#d681fb', 'purple'), ('#627b87', 'gray')], default='#1976d2', help_text='default color of project', max_length=8)),
                ('status', models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('closed', 'closed')], default='active', help_text='status of project', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='boards', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
