# Generated by Django 5.2.4 on 2025-08-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(choices=[('#1976d2', 'blue'), ('#6ce272', 'green'), ('#ffd36c', 'yellow'), ('#ff7272', 'red'), ('#d681fb', 'purple'), ('#627b87', 'gray')], default='#1976d2', help_text='default color of project', max_length=16),
        ),
    ]
