# Generated by Django 5.2.4 on 2025-08-06 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_team_alter_board_color'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(choices=[('#1976d2', 'blue'), ('#6ce272', 'green'), ('#ffd36c', 'yellow'), ('#ff7272', 'red'), ('#d681fb', 'purple'), ('#627b87', 'gray')], default='#1976d2', help_text='Board color (default: blue)', max_length=16),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, help_text='Board description (optional)'),
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Board team members', related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(help_text='Name of the project or board', max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(help_text='User who created/owns the board', on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed')], default='active', help_text='Status of the board', max_length=16),
        ),
        migrations.AlterField(
            model_name='board',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this board belongs to (can be empty)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='teams.team'),
        ),
    ]
